### ISSUE TITLE
Improve guide for PDF-viewer Dark Mode

### ISSUE THREAD

**Issue by ZeliTheZealot** [hasecilu/Dark-TeXstudio#1]
I know there is an existing rudimentary way of achieving Dark Mode in the PDF Viewer, but some people might prefer a dark grey background instead. 

I have the following setup to make the embedded PDF viewer also behave as Dark Mode.

(inspiration: https://tex.stackexchange.com/questions/267362/texstudio-how-to-change-color-of-internal-pdf-viewer)

1.  Preferences - Internal PDF Viewer - Paper Color - #D1CFCF (light gray)
2. Switch to windowed mode (using Preferences - Build - PDF Viewer)
3. Compile and view (the windowed PDF viewer should show up)
4. In the menu bar, do Configure -> Invert Colors.
5. Switch back to embedded mode.

**Comment by hasecilu** [comment]
Sorry for the delay in responding, I had not realized the message.
I have already updated the guide with the new information.
