### ISSUE TITLE
A few feedback points

### ISSUE THREAD

**Issue by ZeliTheZealot** [hasecilu/Dark-TeXstudio#2]
First of all -- well done! Much better than the Solarized theme I think. However, there are some feedback from me. I will update this as I go along. 

1. Please offer the option of Dark Gray background instead of Black
2. There is low contrast between background and the keywords `\begin`, `\section`, `\subsection`, `\end`.
3. Commands within math environments are harder to see (their arguments are fine). For example, in `\mathbb{N}`, the dark blue of `\mathbb` is harder to see than the light mint `{N}`.
4. The argument of `\label` is hard to see if they're duplicated in multiple figures, for example the `asdf` in `label{asdf}`, if two figures have this same label.

**Comment by hasecilu** [comment]
Thanks for your feedback.

1. - Done.
2. - Yeah, seeing it in detail is slightly difficult to see.  Maybe a lighter blue will work.
3. - Generally I have no problem seeing it but when the line is selected is harder to see the commands, I don't know whether to change the command color or the line-highlight color.
4. - I am aware of it, maybe a light purple color will work.

Any color suggestion will be appreciated.
I hope to fix it soon.

**Comment by hasecilu** [comment]
7 months later I can say:

1. Done.
2. Done. I changed to a lighter blue. I think it's ok but need feedback.
3. Done. I didn't change the command color but changed the line highlight color to gray.
4. Done. I changed to a lighter purple.
